import type { Metadata } from "next";
import "./globals.scss";

import { Inter } from "next/font/google";
import { Toaster } from "sonner";

import { Provider } from "@/components/providers/Provider";
import { SocketProvider } from "@/components/providers/SocketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TEST",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Provider>
          <Toaster richColors position="top-right" duration={1500} />
          <SocketProvider>{children}</SocketProvider>
        </Provider>
      </body>
    </html>
  );
}
